### ISSUE TITLE
How to draw the diagram?

### ISSUE THREAD

**Issue by sonnguyen129** [adamiaonr/mlops-zoomcamp-project#1]
Hi @adamiaonr, I am interested in your project's diagram. What applications do you use for this diagram?
Thanks

**Comment by adamiaonr** [comment]
Hi @sonnguyen129 : sorry for the late reply.
The diagram was done in 'Keynote', a Mac OS equivalent to 'PowerPoint'.

**Comment by sonnguyen129** [comment]
Thank you so much.
